name: Deploy App with Promoted Model

on:
  repository_dispatch:
    types: [deploy-app-model]
  workflow_dispatch:
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/telecomcustomerchurn-app
  MODEL_NAME: DecisionTreeTelecomCustomerChurnModel
  MLFLOW_TRACKING_URI: https://dagshub.com/singhdeepakkumar/my-bda-repo.mlflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install mlflow
          pip install mlflow[extras]

      - name: Download promoted model from MLflow
        env:
          PROMOTED_VERSION: ${{ github.event.client_payload.model_version }}
        run: |
          python <<EOF
          import os
          import mlflow
          from mlflow.tracking import MlflowClient

          model_name = os.environ["MODEL_NAME"]
          model_uri = f"models:/{model_name}@production"
          target_dir = "app_model"

          print(f"Downloading model from alias: production ({model_uri})")

          mlflow.artifacts.download_artifacts(
              artifact_uri=model_uri,
              dst_path=target_dir
          )

          print(f"Model downloaded to: {target_dir}")

          version_file = os.path.join("app_model", "model_version.txt")
          with open(version_file, "w") as f:
              f.write(os.getenv("PROMOTED_VERSION", "unknown"))

          print("Model downloaded and version recorded.")
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          VERSION=model-${{ github.event.client_payload.model_version }}
          docker build -t $DOCKER_IMAGE:$VERSION .
          docker push $DOCKER_IMAGE:$VERSION

      #- name: SSH into GCP VM and deploy container
      #  uses: appleboy/ssh-action@v0.1.6
      #  with:
      #    host: ${{ secrets.GCP_VM_IP }}
      #    username: ${{ secrets.GCP_VM_USER }}
      #    key: ${{ secrets.GCP_VM_SSH }}
      #    script: |
      #      docker pull $DOCKER_IMAGE:model-${{ github.event.client_payload.model_version }}
      #      docker stop churn-app || true
      #      docker rm churn-app || true
      #      docker run -d -p 5000:5000 --name churn-app \
      #        -e MODEL_VERSION=${{ github.event.client_payload.model_version }} \
      #       $DOCKER_IMAGE:model-${{ github.event.client_payload.model_version }}
